# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 build:
   name: Build
   runs-on: self-hosted
   steps:
     - name: Login to Private Container Registry
       uses: docker/login-action@v2
       with:
         registry: ${{ secrets.REGISTRY_URL }}
         username: ${{ secrets.REGISTRY_USERNAME }}
         password: ${{ secrets.REGISTRY_PASSWORD }}

     - name: Build and push Docker image
       uses: docker/build-push-action@v3
       with:
         push: true
         tags: |
           ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest
           ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
 deploy:
   needs: [build]
   name: Deploy
   runs-on: self-hosted
   steps:
     - name: Set Kubernetes context
       uses: Azure/k8s-set-context@v3
       with:
         method: kubeconfig
         kubeconfig: ${{ secrets.KUBE_CONFIG }}
     - name: Trigger Restart and pull new image
       run: kubectl rollout restart deployment deployment-lbboltgf --namespace=prod
